### ISSUE TITLE
Error trying to convert localization

### ISSUE THREAD

**Issue by LiaNdrY** [hhrhhr/LuaELEX#4]
H:\xxx\ELEX\data\packed\c_1_na\localization\LuaELEX-master>lua w_strings.lua w_strings.bin output.lua 0
lua: ...c_1_na\localization\LuaELEX-master\mod_binary_reader.lua:186:

ERROR: ☺
stack traceback:
        [C]: in function 'assert'
        ...c_1_na\localization\LuaELEX-master\mod_binary_reader.lua:186: in method 'idstring'
        w_strings.lua:219: in local 'read_GAR5'
        w_strings.lua:234: in main chunk
        [C]: in ?

Game version 1.0.2946.0

**Comment by hhrhhr** [comment]
Can you share your _w_strings.bin_?

**Comment by LiaNdrY** [comment]
Sure, http://dropmefiles.com/Wx2AT

**Comment by hhrhhr** [comment]
I think that either the developers changed the format of the language file, or you unpacked the wrong file, or the unpacker worked incorrectly.
![elex_lang_issue](https://user-images.githubusercontent.com/966048/34471536-5680fa34-ef5d-11e7-802b-92fca8c0d119.png)
On the left is the old file (1.0.2846.0), on the right is yours. Unfortunately, now I do not have access to the updated version of the game, so I can not confirm or disprove my assumption.

**Comment by LiaNdrY** [comment]
And with what utility did you unpack the file c_1_na.pak?

**Comment by LiaNdrY** [comment]
I apologize, I unpacked c_1_na.pak with the help of the utility elexresman and it all worked. The question is solved.
