### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by newman55** [hhrhhr/LuaELEX#5]
Привет. Извини за эту тему. Не знал как с тобой связаться. 
Могу ли я использовать твои карты для subnautica?
Вот эти https://github.com/MartinSGill/SubnauticaWatcher/issues/7
в своем моде https://www.nexusmods.com/subnautica/mods/12

**Comment by hhrhhr** [comment]
Учитывая то, что я публикую эти карты путем рендеринга игровых ресурсов безо всякого разрешения со стороны разработчиков, не вижу причин для каких либо ограничений со своей стороны.
Однако, более актуальные версии я выкладывал на [оффоруме](https://forums.unknownworlds.com/discussion/147269/maps-in-games-folder/p2), также там есть ссылки на "исходники" (вдруг цвета захочется сменить или что-то типа этого).

**Comment by newman55** [comment]
Премного благодарен
